version: '3.3'

services:
  db: # container de mysql
    image: mysql:5.7 # no arquivo Dockerfile é equivalente ao FROM mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: gustavo
      MYSQL_PASSWORD: secret

  wordpress: 
    depends_on:
      - db
    image: wordpress:latest
    ports: 
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: gustavo
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

# é necessário criar uma chave 'volumes' pois é necessário declarar todos os volumes declados na aplicaçao
volumes: 
  db_data: {}
