version: '3.3'

services:
  db: # container de mysql
    image: mysql:5.7 # no arquivo Dockerfile é equivalente ao FROM mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    env_file: 
      - ./config/db.env
    networks: # declara a network que esse serviço estará conectada
      - backend

  wordpress: 
    depends_on:
      - db
    image: wordpress:latest
    ports: 
      - "8000:80"
    restart: always
    env_file: 
      - ./config/wp.env
    networks: # declara a network que esse serviço estará conectada
      - backend
# é necessário criar uma chave 'volumes' pois é necessário declarar todos os volumes declados na aplicaçao
volumes: 
  db_data: {}

# assim como em volumes, devemos criar uma chave especificando que o compose deverá criar as networks ditas no arquivo
networks: 
  backend: 